NepalPayementTest/Models/ErrorViewModel.cs
using System;

namespace NepalPayementTest.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NepalPayementTest/Models/TaskType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NepalPayementTest.Models
{
    public enum TaskType
    {
        TaskType1,
        TaskType2,
        TaskType3,
        TaskType4,
        TaskType5

    }
}

NepalPayementTest/Models/UserTask.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NepalPayementTest.Models
{
    public class UserTask
    {
        public Guid Id { get; set; }
        public string TaskName { get; set; }
        public DateTime AssignDate { get; set; }
        public DateTime DeadlineDead { get; set; }
        public TaskType TaskType { get; set; }

    }
}

NepalPayementTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NepalPayementTest.Models;

namespace NepalPayementTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NepalPayementTest/Controllers/UserTasksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NepalPayementTest.Data;
using NepalPayementTest.Models;

namespace NepalPayementTest.Controllers
{
    [Authorize()]
    public class UserTasksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UserTasksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: UserTasks
        public async Task<IActionResult> Index()
        {
            return View(await _context.UserTask.ToListAsync());
        }

        // GET: UserTasks/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userTask = await _context.UserTask
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userTask == null)
            {
                return NotFound();
            }

            return View(userTask);
        }

        // GET: UserTasks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserTasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TaskName,AssignDate,DeadlineDead,taskType")] UserTask userTask)
        {
            if (ModelState.IsValid)
            {
                userTask.Id = Guid.NewGuid();
                _context.Add(userTask);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(userTask);
        }

        // GET: UserTasks/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userTask = await _context.UserTask.FindAsync(id);
            if (userTask == null)
            {
                return NotFound();
            }
            return View(userTask);
        }

        // POST: UserTasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,TaskName,AssignDate,DeadlineDead,TaskType")] UserTask userTask)
        {
            if (id != userTask.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userTask);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserTaskExists(userTask.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(userTask);
        }

        // GET: UserTasks/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var userTask = await _context.UserTask
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userTask == null)
            {
                return NotFound();
            }

            return View(userTask);
        }

        // POST: UserTasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var userTask = await _context.UserTask.FindAsync(id);
            _context.UserTask.Remove(userTask);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserTaskExists(Guid id)
        {
            return _context.UserTask.Any(e => e.Id == id);
        }
    }
}

NepalPayementTest/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NepalPayementTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NepalPayementTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NepalPayementTest</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserTasks" asp-action="Index">Task</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - NepalPayementTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

NepalPayementTest/Views/UserTasks/Create.cshtml
@model NepalPayementTest.Models.UserTask

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>UserTask</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TaskName" class="control-label"></label>
                <input asp-for="TaskName" class="form-control" />
                <span asp-validation-for="TaskName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssignDate" class="control-label"></label>
                <input asp-for="AssignDate" class="form-control" />
                <span asp-validation-for="AssignDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeadlineDead" class="control-label"></label>
                <input asp-for="DeadlineDead" class="form-control" />
                <span asp-validation-for="DeadlineDead" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="taskType" class="control-label"></label>
        <select asp-for="taskType" class="form-control"></select>
        <span asp-validation-for="taskType" class="text-danger"></span>*@
                <label asp-for="TaskType" class="control-label"></label>
                <select asp-for="TaskType" class="custom-select mr-sm-2"
                        asp-items="Html.GetEnumSelectList<TaskType>()">
                    <option value="">Please Select</option>
                </select>
                <span asp-validation-for="TaskType" class="text-danger"></span>

            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NepalPayementTest/Views/UserTasks/Delete.cshtml
@model NepalPayementTest.Models.UserTask

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserTask</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaskName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaskName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AssignDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AssignDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeadlineDead)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeadlineDead)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaskType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaskType)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

NepalPayementTest/Views/UserTasks/Details.cshtml
@model NepalPayementTest.Models.UserTask

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>UserTask</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaskName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaskName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AssignDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AssignDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DeadlineDead)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DeadlineDead)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaskType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaskType)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

NepalPayementTest/Views/UserTasks/Edit.cshtml
@model NepalPayementTest.Models.UserTask

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>UserTask</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="TaskName" class="control-label"></label>
                <input asp-for="TaskName" class="form-control" />
                <span asp-validation-for="TaskName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AssignDate" class="control-label"></label>
                <input asp-for="AssignDate" class="form-control" />
                <span asp-validation-for="AssignDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DeadlineDead" class="control-label"></label>
                <input asp-for="DeadlineDead" class="form-control" />
                <span asp-validation-for="DeadlineDead" class="text-danger"></span>
            </div>
            <div class="form-group">
                @*<label asp-for="taskType" class="control-label"></label>
        <select asp-for="taskType" class="form-control"></select>
        <span asp-validation-for="taskType" class="text-danger"></span>*@
                <label asp-for="TaskType" class="control-label"></label>
                <select asp-for="TaskType" class="custom-select mr-sm-2"
                        asp-items="Html.GetEnumSelectList<TaskType>()">
                    <option value="">Please Select</option>
                </select>
                <span asp-validation-for="TaskType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NepalPayementTest/Views/UserTasks/Index.cshtml
@model IEnumerable<NepalPayementTest.Models.UserTask>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TaskName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AssignDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeadlineDead)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TaskType)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TaskName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AssignDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DeadlineDead)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TaskType)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>